Add pytype testing options (#499)
* Enable pytype variable type checking

- Add type concept for index selection types
- Enable precise return checking for invalid function calls
- Test solve unknown types to label with structural types

Add conceptual type for dictionary selection variables

Values used to select dictionary subsets must be
containers of hashable elements.

File "monai/monai/transforms/io/dictionary.py", line 55, in __init__:
Function LoadNiftid.__init__ was called with the wrong arguments [wrong-arg-types]
         Expected: (self, keys: Container[Hashable])
  Actually passed: (self, keys: Hashable)
  The following methods aren't implemented on Hashable:
  __iter__

* Avoid conversion function for static valued initializer

File "monai/monai/transforms/croppad/dictionary.py", line 136, in randomize: Function monai.utils.misc.ensure_tuple was called with the wrong arguments [wrong-arg-types]
         Expected: (vals: Iterable)
  Actually passed: (vals: slice)
  The following methods aren't implemented on slice:
  __iter__

* `keys` to accept either Collection[Hashable] or [Hashable]

For backward compatibility, allow `keys` to accept either
a collection or a hashable item.  change self.keys to have
the required more strict value type than the
function parameter `keys`.

* Fix Incompatible types in assignment

monai/transforms/intensity/dictionary.py:334: error: Incompatible types in assignment
  (expression has type "Union[Tuple[Any, ...], List[Any]]", variable has type "Tuple[float, Any]")

Signed-off-by: Nic Ma <nma@nvidia.com>