Fix OptionalImportError: required package `openslide` is not installed
The full error message was:

monai.utils.module.OptionalImportError: required package `openslide` is not installed or the version doesn't match requirement.

More details in:
https://github.com/Project-MONAI/tutorials/discussions/1949