Resolve tests.test_convolutions failure due to relative path resolution
from .utils import TorchImageTestCase2D
ImportError: attempted relative import with no known parent package