Fix optional import error.
Due to the removal of the long-deprecated pkgutil.ImpImporter class
a newer version of setuptools that provides this capability.
for Python 3.12.

This resolves:

monai.utils.module.OptionalImportError: Please install mlflow
before using MLFlowHandler. (module 'pkgutil' has no attribute 'ImpImporter').

Signed-off-by: Hans Johnson <hans-johnson@uiowa.edu>