#6213 Prepend `"meta"` to `MetaTensor.__repr__` and `MetaTensor.__str__` for easier identification (#6214)
Discussed in #6213

### Description

Prepends `"meta"` to the `MetaTensor.__repr__` and `MetaTensor.__str__`
output so printing a MetaTensor does not look the exact same as a
regular `torch.Tensor`.

I don't expect this change to cause any breaks, with me running the risk
of invoking [xkcd 1172](https://xkcd.com/1172/).

---

1 failure in `./runtests.sh -f -u --net --coverage`:
```text
======================================================================
FAIL: test_values (tests.test_tciadataset.TestTciaDataset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\PythonProjects\MONAI-SaveImageFormatting\tests\test_tciadataset.py", line 72, in test_values
    self.assertTrue(
AssertionError: False is not true
```

### Types of changes
<!--- Put an `x` in all the boxes that apply, and remove the not
applicable items -->
- [x] Non-breaking change (fix or new feature that would not break
existing functionality).
- [x] New tests added to cover the changes.
- [x] Integration tests passed locally by running `./runtests.sh -f -u
--net --coverage`.
- [x] Quick tests passed locally by running `./runtests.sh --quick
--unittests --disttests`.
- [x] In-line docstrings updated.

---------

Signed-off-by: Mathijs de Boer <m.deboer-41@umcutrecht.nl>